### PR TITLE
Fix file system tree invalidation

### LINKED ISSUE #269: Local Changes tab not picking up the changes with the Reactive client if refreshed manually
1. Make sure you use the Reactive client
2. Make any change in a file under TFVC (but do not save yet)
3. Press the **Refresh** button in the **Local Changes** tab
4. Now press Ctrl-S (Cmd-S) to save all the files (or change focus to non-Rider window)

**Expected result:** **Local Changes** tab should be populated by changes
**Observed result:** it won't include the file you've changed

According to my experiments, it won't work after any amount of refreshing, until you've changed the same file again.

### PR DESCRIPTION
**Pull request by ForNeVeR**
This PR has two distinct changes that improve the situation with the **Local Changes** tab for both classic and reactive clients.

First of all, TFVC clients never pick up the unsaved changes from the editor anyway, so the `isModifiedDocumentTrackingRequired` flag shouldn't be set to true. This change will improve the UX a little bit for both clients, because they won't update the change lists before any changes are actually made in the file system.

But this flag was breaking the new reactive client even more, because the client won't properly pick up the changes after manual refresh: manual refresh triggers invalidation of the root item in the tree, and the subsequent save won't trigger any invalidation at all.

So, I've decided to make the **Refresh** button to trigger invalidation of the whole file system tree as intended, by doing small enhancement of our reactive file system watcher. TFS SDK already have the necessary API, so I just had to start using it.

Closes #269.

### CODE REVIEW

File: client/backend/src/main/kotlin/com/microsoft/tfs/watcher/ExternallyControlledPathWatcher.kt [hunk 1]
```diff
@@ -60,23 +61,34 @@ class ExternallyControlledPathWatcher(
     override fun isWatching(): Boolean = currentSessionLifetime.isAlive
 
     override fun poll(): PathWatcherReport {
-        val changes = synchronized(lock) {
-            val copy = changedPaths.toList()
+        val (fullyInvalidated, changes) = synchronized(lock) {
```
Comment (mfilippov) [inline client/backend/src/main/kotlin/com/microsoft/tfs/watcher/ExternallyControlledPathWatcher.kt]: I don't like pair in this place.

Comment (ForNeVeR) [reply client/backend/src/main/kotlin/com/microsoft/tfs/watcher/ExternallyControlledPathWatcher.kt]: Thanks, fixed!
