### PR TITLE
Fix for case-insensitive file systems and IDEA change provider

### LINKED ISSUE #274: Change list stops being updated if workspace path isn't in the same case as path on disk
1. Clone the TFVC repository e.g. to `C:\tfs\vs\project`
2. Change the case on disk (e.g. rename `vs` to `VS`)
3. Now open the project, change any file and press Ctrl-S

**Expected:** the change should appear on the **Local Changes** list
**Actual:** the change won't appear

Both classic and reactive clients are affected.

### PR DESCRIPTION
**Pull request by ForNeVeR**
The change provider should report paths in the same case as they are on disk. Otherwise, there will be random omissions of changes (see #274 for details).

Closes #274.

### CODE REVIEW

File: plugin/src/com/microsoft/alm/plugin/idea/tfvc/core/tfs/VersionControlPath.java [hunk 1]
```diff
@@ -60,9 +73,9 @@ public static String localPathFromTfsRepresentation(@Nullable String localPath)
 
         final String systemDependent = FileUtil.toSystemDependentName(localPath);
         if (!SystemInfo.isWindows && systemDependent.startsWith(FAKE_DRIVE_PREFIX)) {
-            return systemDependent.substring(FAKE_DRIVE_PREFIX.length());
+            return canonicalizePath(systemDependent.substring(FAKE_DRIVE_PREFIX.length()));
```
Comment (mfilippov) [inline plugin/src/com/microsoft/alm/plugin/idea/tfvc/core/tfs/VersionControlPath.java]: Maybe we shouldn't use toSystemDependentName and canonicalize in same time.
